class Consts():

    IMG_WIDTH = 800
    IMG_HEIGHT = 400
    CENTER_TOLERANCE = 6
    DISTANCE_FOR_CLOSE_CONTOURS = 60
    SEEN_ANIMAL_COUNTER = 3
    TIME_TO_GRAB = 3
    TIME_TO_LAST_IR_TICK = 500000
