class Consts():

    IMG_WIDTH = 800
    IMG_HEIGHT = 400
    CENTER_TOLERANCE = 6
    DISTANCE_FOR_CLOSE_CONTOURS = 60
    SEEN_ANIMAL_COUNTER = 3
    
    TIME_TO_GRAB = 3
    TIME_TO_LAST_IR_TICK = 500000
    TIME_TO_DRIVE_INTO_TARGET = 3

    #normal Speed:
    MOTOR_WHEELS_FREQUENCY = 10000
    MOTOR_WHEELS_DUTYCYLCE = 750000
    #Speed when animal is on screen:
    MOTOR_WHEELS_FREQUENCY_SLOW = 1000
    MOTOR_WHEELS_DUTYCYLCE_SLOW = 300000
    #Speed to drive into target:
    MOTOR_WHEELS_FREQUENCY_TARGET = 4000
    MOTOR_WHEELS_DUTYCYLCE_TARGET = 500000
    #Speed for one wheel (left or right) while steering:
    MOTOR_WHEELS_FREQUENCY_STEER = 10000
    MOTOR_WHEELS_DUTYCYLCE_STEER = 750000

    GPIO_IR_SENSOR_LEFT = 22
    GPIO_IR_SENSOR_RIGHT = 24
